--- #YAML:1.0
name:               Archive-Lha
version:            0.06
abstract:           extract .LZH archives
author:
    - Kenichi Ishigaki <ishigaki@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Data::Dump:           0
    Exporter::Lite:       0
    Fcntl:                0
    File::Basename:       0
    File::Path:           0
    File::Slurp:          0
    File::Spec:           0
    List::Util:           0
    Log::Dispatch:        0
    Test::More:           0.47
    Test::UseAllModules:  0.09
    Time::Piece:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
