--- #YAML:1.0
name:                Archive-Lha
version:             0.02
abstract:            extract .LZH archives
license:             perl
author:              
    - Kenichi Ishigaki <ishigaki@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    Data::Dump:                    0
    Exporter::Lite:                0
    Fcntl:                         0
    File::Basename:                0
    File::Path:                    0
    File::Slurp:                   0
    File::Spec:                    0
    List::Util:                    0
    Log::Dispatch:                 0
    Test::More:                    0.47
    Test::UseAllModules:           0
    Time::Piece:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
